# provide the reboot command
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: node-restart-sa
  experiments:
  - name: node-restart
    spec:
      components:
        env:
        # command used for the reboot
        #- name: REBOOT_COMMAND
          #value: 'sudo systemctl reboot'
        - name: TARGET_NODE_IP
          value: '192.168.25.77'
        # name of the target node
        - name: TARGET_NODE
          value: 'i-016f25bb974ef4e2d'
        - name: TOTAL_CHAOS_DURATION
          VALUE: '60'
